spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.use-code-as-default-message=true
server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

telegram.bot.token=${BOT_TOKEN}
telegram.bot.username=${BOT_USERNAME}
app.hmac-secret=${API_HMAC_SECRET}
app.allowed-origin=${APP_ALLOWED_ORIGIN}