spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.use-code-as-default-message=true
server.port=${PORT:8080}
server.address=0.0.0.0

telegram.bot.token=${BOT_TOKEN}
telegram.bot.username=${BOT_USERNAME}
app.hmac-secret=${API_HMAC_SECRET}
app.allowed-origin=${APP_ALLOWED_ORIGIN}
app.public.url=${PUBLIC_URL}